CC = gcc
CFLAGS = -Og -Wall -Werror
LDLIBS = -lpthread

mysystem: 822_mysystem.c csapp.c
	$(CC) $(CFLAGS) -o mysystem 822_mysystem.c csapp.c $(LDLIBS)

psignal: 824_psignal.c csapp.c
	$(CC) $(CFLAGS) -o psignal  824_psignal.c csapp.c $(LDLIBS)